#   $$$$$$\
#  $$  __$$\
# $$ /  \__| $$$$$$\   $$$$$$\ $$\    $$\  $$$$$$\   $$$$$$\
# \$$$$$$\  $$  __$$\ $$  __$$\\$$\  $$  |$$  __$$\ $$  __$$\
#  \____$$\ $$$$$$$$ |$$ |  \__|\$$\$$  / $$$$$$$$ |$$ |  \__|
# $$\   $$ |$$   ____|$$ |       \$$$  /  $$   ____|$$ |
# \$$$$$$  |\$$$$$$$\ $$ |        \$  /   \$$$$$$$\ $$ |
#  \______/  \_______|\__|         \_/     \_______|\__|
#By ItsJxsper

prefix: "<blue><hover:show_text:'<gray>By ItsJxsper</gray>'><server></hover></blue> <gray>→</gray> "

config:
  invincibility.enabled: true
  invincibility.duration: 5

message:
  join: "<color:#49b675>+</color> <gray><player></gray>"
  quit: "<color:#ff6961>-</color> <gray><player></gray> "

message.commands:
  command.no-permission: "<red>Du hast keine Berechtigung diesen Befehl auszuführen!</red>"
  command.only-players: "<red>Dieser Befehl kann nur von Spielern ausgeführt werden!</red>"
  spawn.success: "<green>Du wurdest zum World-Spawn teleportiert</green>"
  back.success: "<green>Du wurdest zum letzten Ort teleportiert</green>"
  back.no-back-coordinates: "<red>Du hast keine Back-Koordinaten gespeichert!</red>"
  tpa.specify-player: "<red>Du musst einen Spieler angeben!</red>"
  tpa.teleport-success: "<green>Teleport erfolgreich!</green>"
  tpa.cannot-teleport-to-self: "<red>Du kannst dich nicht zu dir selbst teleportieren!</red>"
  tpa.player-offline: "<red>Der Spieler ist offline!</red>"
  tpa.no-pending-requests: "<red>Du hast keine ausstehende Teleport-Anfrage!</red>"
  tpa.request-declined: "<red>Teleport-Anfrage von <player> abgelehnt!</red>"
  tpa.request-rejected: "<red>Teleport-Anfrage an <player> abgelehnt!</red>"
  tpa.request-accepted: "<green>Teleport-Anfrage von <player> akzeptiert!</green>"
  tpa.request-sent: "<green>Teleport-Anfrage an <player> gesendet!</green>"
  tpa.request-received: "<green>Teleport-Anfrage von <player> erhalten!</green> \n <click:run_command:'/tpaaccept'><gray>[<green>Accept</green>]</gray></click> <click:run_command:'/tpadeny'><gray>[<red>Deny</red>]</gray></click>"
  tpa.already-requested: "<red>Du hast bereits eine Teleport-Anfrage gesendet!</red>"
  tpahere.request-sent: "<green>Teleport-Here Anfrage an <player> gesendet!</green>"
  tpahere.request-received: "<green>Teleport-Here Anfrage von <player> erhalten!</green> \n <click:run_command:'/tpaccept'><gray>[<green>Accept</green>]</gray></click> <click:run_command:'/tpdeny'><gray>[<red>Deny</red>]</gray></click>"
  nightvision.enabled: "<green>Nachtsicht aktiviert!</green>"
  nightvision.disabled: "<red>Nachtsicht deaktiviert!</red>"

database:
  message.not-connected: "Du bist nicht mit der Datenbank verbunden!"
