#   $$$$$$\
#  $$  __$$\
# $$ /  \__| $$$$$$\   $$$$$$\ $$\    $$\  $$$$$$\   $$$$$$\
# \$$$$$$\  $$  __$$\ $$  __$$\\$$\  $$  |$$  __$$\ $$  __$$\
#  \____$$\ $$$$$$$$ |$$ |  \__|\$$\$$  / $$$$$$$$ |$$ |  \__|
# $$\   $$ |$$   ____|$$ |       \$$$  /  $$   ____|$$ |
# \$$$$$$  |\$$$$$$$\ $$ |        \$  /   \$$$$$$$\ $$ |
#  \______/  \_______|\__|         \_/     \_______|\__|
#By ItsJxsper

prefix: "<blue><hover:show_text:'<gray>By ItsJxsper</gray>'>Server</hover></blue> <gray>â†’</gray>"

message:
  join: "<color:#49b675>+</color> <gray><player></gray>"
  quit: "<color:#ff6961>-</color> <gray><player></gray> "